require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "Gemfile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: expanded

RSpec/NotToNot:
  EnforcedStyle: to_not

Naming/VariableNumber:
  Description: checks the style of numbered variables
  Enabled: true
  EnforcedStyle: snake_case

Style/FrozenStringLiteralComment:
  Description: >-
    Add the frozen_string_literal comment to the top of files
    to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "test/factories/*"

Style/ClassAndModuleChildren:
  Description: Checks style of children classes and modules.
  Enabled: false
  EnforcedStyle: compact
  SupportedStyles:
  - nested
  - compact

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: either

Style/HashLikeCase:
  MinBranchesCount: 4

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - before
    - after
    - during

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 7
