version: "3"
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  app:
    build:
      context: containers/rails
    volumes:
      - ./containers/rails:/tyakudon
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    tty:
      true
    stdin_open: true
    depends_on:
      - db

volumes:
  postgresql-data:
